version: '3'
services:
  db:
    image: postgres:latest
    restart: always
    user: postgres
    secrets:
      - db-password
    environment:
      POSTGRES_DB: crux_db
      POSTGRES_PASSWORD_FILE: /run/secrets/db-password
    volumes:
      - ./database/init_scripts:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

  server:
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    restart: always
    volumes:
      - ./server:/src
    secrets:
      - db-password
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:5000/test"]
      interval: 30s
      timeout: 10s
      retries: 3
    depends_on:
      db:
        condition: service_healthy
        restart: true

  web:
    build:
      dockerfile: Dockerfile.dev
      context: ./frontend
    restart: always
    volumes:
      - ./frontend:/app
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web
      - server
      
secrets:
  db-password:
    file: database/db_pass.txt
