# Use an official Python runtime as a parent image
FROM python:latest

# Set the working directory to /app
WORKDIR /src

COPY requirements.txt requirements.txt

ENV PYTHONUNBUFFERED=1

RUN pip3 install -r requirements.txt

CMD ["python3", "app.py"]